# Generated by Django 3.1.6 on 2021-02-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Bus',
        ),
    ]
