# Generated by Django 3.1.6 on 2021-02-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210203_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='check',
            field=models.IntegerField(default=0),
        ),
    ]
