# Generated by Django 3.1.6 on 2021-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210203_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
