# Generated by Django 3.1 on 2021-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
